# Generated by Django 2.2.5 on 2020-03-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20200304_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default='media/images/', null=True, upload_to='media/images/'),
        ),
    ]
