# Generated by Django 2.2.5 on 2020-03-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_auto_20200315_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subtwocategory',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
